name       : botan2
version    : 2.17.3
release    : 11
source     :
    - https://github.com/randombit/botan/archive/2.17.3.tar.gz : 544c62e43be0c60fff7ac8707ee99fe134c75bef06bded217d04f0a4b333519a
license    : BSD-2-Clause
component  : programming.library
summary    : Crypto and TLS library for C++11
description: |
    Botan's goal is to be the best option for cryptography in C++ by offering the tools necessary to implement a range of practical systems, such as TLS protocol, X.509 certificates, modern AEAD ciphers, PKCS#11 and TPM hardware support, password hashing, and post quantum crypto schemes. A Python binding is included.
optimize   :
    - speed
setup      : |
    python3 ./configure.py        \
        --disable-static-library  \
        --distribution-info=Solus \
        --libdir=%libdir%         \
        --prefix=%PREFIX%         \
        --without-documentation
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
