name       : botan2
version    : 2.12.1
release    : 3
source     :
    - https://github.com/randombit/botan/archive/2.12.1.tar.gz : 61d27332f053b0b1169659dc0fceb7de7d16cade230df3a14dfaa2c091888b98
license    : BSD-2-Clause
component  : programming.library
summary    : Crypto and TLS for Modern C++
description: |
    Botan's goal is to be the best option for cryptography in C++ by offering the tools necessary to implement a range of practical systems, such as TLS protocol, X.509 certificates, modern AEAD ciphers, PKCS#11 and TPM hardware support, password hashing, and post quantum crypto schemes. A Python binding is included, and several other language bindings are available.
setup      : |
    python3 ./configure.py --disable-static-library --prefix=%PREFIX% --cpu=%ARCH% --os=linux \
                           --libdir=%libdir% --mandir=/usr/share/man --infodir=/usr/share/info \
                           --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var \
                           --bindir=%libdir%/%PKGNAME% --cxxflags='%CXXFLAGS%' --ldflags='%LDFLAGS%' \
                           --cc=gcc --without-documentation
build      : |
    %make
install    : |
    %make_install
